language: python

python:
  - "3.6"
  
 env:
  - DJANGO=1.10.5
  
 branches:
  only:
    - master
    
before_install:
      - export DJANGO_SETTINGS_MODULE=frisor.settings
      - export SECRET_KEY='This is secret'
      - export DEBUG=True
      
install:
  - pip install -r requirements.txt
  
script: 
  - cd frisor
  - coverage run --source=frisor_urls,frisor manage.py test
  
after_success:   
  - coverage report
  - coveralls

