language: python
sudo: false

python:
  - "3.5"

cache:
  directories:
  - "$HOME/.cache/pip"
  
env:
  - DJANGO=1.10.5

branches:
  only:
    - master

install:
  - pip install coverage
  - pip install coveralls
  - pip install -r requirements.txt

before_install:
  - export DJANGO_SETTINGS_MODULE=frisor.settings
  - export SECRET_KEY='This is secret'
  - export DEBUG=True

script:
  - cd frisor
  -  coverage run --source=frisor_urls,frisor manage.py test


after_success:
  - coverage report
  - coveralls
