#all a test
language: python
python:
  - "3.6"
cache:
  directories:
  - "$HOME/.cache/pip"
before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y python-numpy
      - pip3 install python3-xlib
      - sudo apt-get install scrot
      - sudo apt-get install python3-tk
      - sudo apt-get install python3-dev
      #- pip3 install pyautogui
install:
  - pip install -r requirements.txt
script: pytest
after_success: coverage report

