#all a test
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coverage
script: python setup.py install
after_success: coverage report
