#all a test
language: python
python:
  - "3.6"
cache:
  directories:
  - "$HOME/.cache/pip"
before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y python-numpy
      - pip3 install python3-xlib
      - sudo apt-get install scrot
      - sudo apt-get install python3-tk
      - sudo apt-get install python3-dev
      #- pip3 install pyautogui
env:
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.5
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
script: trial PUBG-Afk-Credit-Bot
after_success: coverage report

